# Site settings
title: fernetjs
name: fernetjs
email: equipo@fernetjs.com
description: fernet + javascript
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fernetjs.com" # the base hostname & protocol for your site
twitter_username: fernetjs
github_username:  fernetjs

# Build settings
markdown: kramdown
highlighter: pygments
